Abosede a
Chameleon-company/MOP-Code pull request #55
Opened 2022-10-05 23:15 UTC by abosedealli

Adding this Smart bin and disposal optimization,

2022-10-06 07:04 UTC, breemclennan reviewed
Hi Bose,
Well done on creating this python notebook for the smart bin use case. You've covered some very intriguing content with the smart bin data.
I would suggest updating the file name for the python notebook to conform to the naming standards applied in the /usecases/ folder in the master branch of the repository. For example 'usecase-SmartBinDisposalOptimisation.ipynb'
Are there any future opportunities for further work which could be applied to this use case? It might be good to capture these in the notebook document or on the Trello card.

Kind regards,
Bree

2022-10-07 04:29 UTC, hannahsm1th requested changes
Hi Bose, could you also move your documentation to the MOPCode/datascience/documentation folder, and update that filename too? The current name is something about blockchain. 
Thanks, 
Hannah.

2022-10-07 04:49 UTC, abosedealli commented
Ops,  thats terrible..am sorry.. will do that now

________________________________
From: Hannah Smith ***@***.***>
Sent: 07 October 2022 15:29
To: Chameleon-company/MOP-Code ***@***.***>
Cc: BOSE ALLI ***@***.***>; Assign ***@***.***>
Subject: Re: [Chameleon-company/MOP-Code] Abosede a (PR #55)


@hannahsm1th requested changes on this pull request.

Hi Bose, could you also move your documentation to the MOPCode/datascience/documentation folder, and update that filename too? The current name is something about blockchain.
Thanks,
Hannah.

—
Reply to this email directly, view it on GitHub<https://github.com/Chameleon-company/MOP-Code/pull/55#pullrequestreview-1133888138>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWRSHPBLS4ZO4DOZSM4PQ7LWB6RMLANCNFSM6AAAAAAQ6AFGPQ>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-10-08 23:36 UTC, hannahsm1th approved these changes

2022-11-07 02:14 UTC, merged