WD_Frontend_PL
Chameleon-company/MOP-Code pull request #567
Opened 2024-05-13 12:45 UTC by plhagyal

Upload Page
-styling fix
-responsive css

2024-05-14 04:33 UTC, adrianweerasinghe97 commented on next_webapp/public/styles/CasestudiesBackup.css
The container class has been defined  twice, once commented out and once active. 

The initial comment starts with /* but does not have the proper closing */. This could cause the rest of the styles to be treated as comments, rendering them inactive.

2024-05-14 04:33 UTC, adrianweerasinghe97 reviewed
In the casestudiesbackup.css file
The container class has been defined twice, once commented out and once active.

The initial comment starts with /* but does not have the proper closing */. This could cause the rest of the styles to be treated as comments, rendering them inactive.

2024-05-14 06:32 UTC, kaseyuu requested changes
Hi Pema, when there are quotation marks such as '' in your text, the system cannot recognize whether they are part of the text or part of the program. The solution is to replace ' with &apos;.

2024-05-15 02:35 UTC, plhagyal commented
> Hi Pema, when there are quotation marks such as '' in your text, the system cannot recognize whether they are part of the text or part of the program. The solution is to replace ' with '.

I haved made the changes. Thanks for the feedback

2024-05-15 02:37 UTC, plhagyal commented
deployment issue has been fixed

2024-05-16 00:31 UTC, kaseyuu approved these changes
Looks nice :)

2024-05-16 00:31 UTC, merged