DATA SCIENCE TEAM- Impact_of_Employment_housingprice Use case
Chameleon-company/MOP-Code pull request #586
Opened 2024-05-15 09:41 UTC by Manasa-n1

This is a final pull request.
Moved all files to Ready to publish folder, Kindly review.

2024-05-15 23:45 UTC, HarleyNgo requested changes
Hi Manasa!
You've put the use case files into the right folder, but please change the name of the files so that they are consistent. The use case looks good to me to be approved.
Also, the document about setup google colab should have both .docx and .pdf versions, and they should be put in folder datascience\documentation.

Please change the above and I'll approve

2024-05-16 02:17 UTC, Manasa-n1 commented
I have made the changes as per the feedback please review it

2024-05-16 03:32 UTC, yashdawaree approved these changes

2024-05-16 22:35 UTC, HarleyNgo approved these changes

2024-05-17 00:26 UTC, merged