initial commit
Chameleon-company/MOP-Code pull request #629
Opened 2024-08-05 13:45 UTC by sinankilci0

Use case proposal
Introduction
Data request
Data wrangling

2024-08-08 01:12 UTC, Samiha-Haque requested changes
Hi Sinan,
1. Please use API2.1v for loading datasets instead read_csv

2024-08-08 04:42 UTC, trostov commented
Hi Sinan, just to add here are the API documentation links:
https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/usecases/ODSQL_API_v2_1_2024_tutorial_v2.ipynb
https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/documentation/Instructions%20for%20ODSQL_API_v2.1_2024.pdf

2024-08-09 00:26 UTC, Samiha-Haque approved these changes
@sinankilci0 Great work! Api2.1v looks good.
Approved.

2024-08-09 06:51 UTC, trostov approved these changes

2024-08-11 13:41 UTC, merged