Data Science Team - Business Establishments in City of Melbourne-15%
Chameleon-company/MOP-Code pull request #657
Opened 2024-08-07 13:09 UTC by nikhilnaga1

Working on Use case, Week 5 pull request for review sprint 1 

- Data Loading and preparation 
- Data Cleaning

2024-08-08 05:40 UTC, dTitanium requested changes
Delete Unnecessary Comments.
Adhere to the use case template.
Ensure all visualizations are correctly labeled.
Describe what you are doing using marksowns.
Describe your use case.

good work! correct above and submit.

2024-08-08 11:32 UTC, ChathuSatharasinghe requested changes
1. Delete the unnecessary  part in the beginning	

2.Comments must have space and capital letter for first word

Eg: # business-establishments-and-jobs-data-by-business-size-and-industry
      # Business establishments and jobs data by business size and industry

3.Give a small explanation on each code block.

Good Work!  Do the nessasry changes and submit.

2024-08-09 11:09 UTC, ChathuSatharasinghe approved these changes

2024-08-09 12:03 UTC, dTitanium approved these changes
beautiful!

2024-08-09 12:26 UTC, merged