Project handover
Chameleon-company/MOP-Code pull request #901
Opened 2024-09-18 12:51 UTC by sinankilci0

- Additional data wrangling
- Combine datasets
- Analysis and report
- Tidy ipynb
- Create html and json

2024-09-19 12:57 UTC, trostov approved these changes
Very nice usecase, good complete writeup with sufficient comments and lots of visualizations . Please change the usecase duration though, its currently set as "6040 minutes". Some of the graphs potentially look a little cluttered, but this is ok if you believe it was the best way to visualize the content.

2024-09-20 22:30 UTC, Samiha-Haque requested changes
@sinankilci0 Amazing usecase! The files look good too.
However a few minor changes are required:
1. Both your maps need legends and a title -> After making the changes I think you need to update the html file as well and use the upload one instead.

2024-09-22 08:55 UTC, trostov approved these changes

2024-09-22 09:07 UTC, Samiha-Haque approved these changes
@sinankilci0 looks good! Approved.

2024-09-22 09:11 UTC, merged